import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import Alert from "@/components/ui/alert";


export const metadata: Metadata = {
  title: "Snazzy Fits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <StoreProvider>
          <ToastContainer />
          <Alert />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
