import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import Alert from "@/components/ui/alert";
import { LiveChatProvider } from "./LiveChatProvider";

export const metadata: Metadata = {
  title: "Snazzy Fits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <StoreProvider>
          <LiveChatProvider>
            <ToastContainer />
            <Alert />
            {children}
          </LiveChatProvider>
        </StoreProvider>

      </body>
    </html >
  );
}
